version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8091:8091"

  discord:
    build:
      context: .
      dockerfile: Dockerfile.discord
    depends_on:
      - api
