version: '3.7'
services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    environment:
      - IS_DOCKER=1
      - RUN_SERVICES=API
      - PORT_NUMBER=8091
  { % for bot_name, bot_config in services.items() % }
  {{bot_name}}:
  build: {{services.build}}
  depends_on: {{services.depends_on}}
  environment:
    - IS_DOCKER=1
    - RUN_SERVICES=DISCORD
    - PORT_NUMBER=8091
  { % endfor % }