services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
    - 8091:8091
    environment:
    - IS_DOCKER=1
  jonbot:
    build:
      context: ..
      dockerfile: docker/Dockerfile.discord
    depends_on:
    - api
    environment:
    - IS_DOCKER=1

version: '3.7'
