# A nickname for the bot, doesn't need to match the actual bot name.
bot_nick_name = "<your bot nick name>"

# Your discord bot token.
discord_token = "<your discord bot token>"

OWNER_IDS = [362711467104927744]

# Names can be anything you want, the actual IDs and details are provided below.
ALLOWED_SERVERS = ["server1_nick_name", "server2_nick_name"]

# Set to true if you want the bot to respond to direct messages.
DIRECT_MESSAGES_ALLOWED = true


# Configuration for server1_nick_name
["server1_nick_name"]
SERVER_ID = 'your server id'
ALLOWED_CATEGORY_IDS = ["ALL"]
ALLOWED_CHANNEL_IDS = ["ALL"]
EXCLUDED_CHANNEL_IDS = []

# Configuration for server2_nick_name
["server2_nick_name"]
SERVER_ID = 'your server id'
ALLOWED_CATEGORY_IDS = ["ALL"]
ALLOWED_CHANNEL_IDS = ["ALL"]
EXCLUDED_CHANNEL_IDS = []

